
// # TypeDoc Tutorial

// In this tutorial you will learn how to document your [TypeScript](https://www.typescriptlang.org/) 
// projects using [TypeDoc](http://typedoc.org/), a tool that will extract descriptions from your TypeScript 
// source comments and generate a well organized and pretty HTML documentation. 

// It is required that you know the basics of TypeScript, but besides that, this tutorial will start from scratch. 




// ## Table of Contents

// <div id="generated-toc"></div>




// ## TypeDoc Introduction

// TypeDoc is an API documentation generator for TypeScript projects, similar 
// to [jsdoc](http://usejsdoc.org/) or [javadoc](https://en.wikipedia.org/wiki/Javadoc).

// Basically, you add documentation comments directly to your source code, right alongside the code itself. The TypeDoc tool will scan your source code and generate an HTML documentation website for you.

// In general you will be documenting entities like classes, interfaces, methods, functions, etc. 

// Although configurable, TypeDoc will generate documentation of everything in your source, even things that are not documented like their names, types and relationships. 

// Unlike JsDoc, with TypeDoc you only take care of descriptions and you never document types, names or member modifiers: that information is already in the TypeScript code!






// ## Descriptions

// For adding a description to some entity in the code you must use special comments that must be placed immediately *before* the code being documented. 

// Each comment must start with a `/**` sequence in order to be recognized by TypeDoc. Comments beginning with `//`, `/*`, `/***`, or more than 3 stars will be ignored. Example: 


/** The sweet and fleshy product of a tree or other plant that contains seed and can be eaten as food. */
class Fruit {

}

// Here you can see the output generated by TypeDoc: [classes/fruit](../../classes/fruit.html).

// TypeDoc will format descriptions with markdown, in concrete it uses the [Marked](https://github.com/chjj/marked) markdown parser and [HighlightJS](https://github.com/isagalaev/highlight.js) to highlight code blocks within markdown sections. In the following example, notice how we use markdown to write multiple paragraphs, bold text and an example code snippet:


/**
 * Responsible of minify given string containing JavaScript code. By default it uses the foo-bar minimization algorithm. 
 * 
 * **Warning: if you don't specify an output in the configuration your input file will be overridden !**
 * 
 * Basic usage example: 
 * 
 * ```ts
 * import {minify} from 'foobar-minify';
 * const config = {
 *   input: readFileSync('dist/awesome-app.js'), 
 *   output: createWriteStream('dist/awesome-app.min.js')
 * }
 *   minify(config);
 * ```
 */
function minify(){}

// Here you can see the output generated by TypeDoc: [globals.html#minify](../../globals.html#minify).





// ## Classes and Interfaces

// First of all, if you are working with interfaces and you intention is that your users work with them and hide the implementation details, then you **should only document** interfaces and never worry about documenting classes. Document classes only to give details about the implementation, if that's what you want, but make sure don't repeat information that's already in the interface.

// In the following example we focus only on classes and interfaces, later we will see [properties](#properties) and [methods](#methods-and-functions) documentation in detail. It declares an interface which is [generic](https://www.typescriptlang.org/docs/handbook/generics.html) and a class implementing it.


/**
 * A shape is the form of an object or its external boundary, outline
 * @param U The unit used to measure the properties of this type of shape
 */
interface Shape<U extends Unit > {
  area():number;
}
interface Unit {}
interface Centimeter extends Unit {} 
/**
 * The Shape implementation used in Foo component to represent Bar
 */
class MyCustomRectangle implements Shape<Centimeter> {
  private side:number;
  public area():number {
    return this.side*this.side;
  }
}



// This is the output of the interface: [interfaces/shape](../../interfaces/shape.html) and this is the output of the class: [classes/mycustomrectangle](../../classes/mycustomrectangle.html)

// Let's take two notes here: 

//  * We used the double star comment (`/**`) just before the interface declaration
//  * The first line of the comment is the interface description
//  * We documented the interface's generic type `U` using the expression `@param U` followed by its description. 








// ## Properties







// ## Methods and Functions

// TODO
//  * overrides and how they look
//  * generic types

// ### Constructors

// constructors can be documented just like any other method






// ## Modules

// TODO






// ## Events

// TODO








// ## Referencing

// When we are describing an entity sometimes we want to reference another entity. For example, when describing the method `Wind.blow()` I want to write a link that points to the class `Ocean` so users can quickly navigate while reading its description. That's what we call referencing. 

// With TypeDoc is very easy to achieve this, you just put the name of the referenced entity between double squared brackets. In the previous example would be [[Ocean]].

// ### Absolute vs. relative references

// You can reference any entity that has a comment like classes, interfaces, methods, functions, properties, etc. You cannot reference a method parameter because it doesn't contain its own comment: the parameter description is inside a method or function comment. 

// Also take in account that a name can be repeated, for example, two classes can contain methods with the same name, or two modules contain classes with the same name. In those cases, the closest entity will takes precedence if we need to reference the external reference we need to use absolute names. Example:


interface Car {
  /** Once started the engine will turn off only when the car travel all the [[Route.size]]*/
  engine:Engine
  size: number
  /** Put in march this cart by turning on its [[engine]] */
  start()
}
interface Route {
  size:number[][]
}
interface Engine{}



// Notes:

//  * In `start` method's description, we just used `[[engine]]` since that property is in the same class: [interfaces/car.html#start](../../interfaces/car.html#start)
//  * But in `engine` property description, for referencing the `Route`'s `size` property, we needed to use its absolute name `Route.size` since `Car` already has a property with that name: [interfaces/car.html#engine](../../interfaces/car.html#engine)


// ### Check for broken references

// if you use a lot of references, you can run the command line tool with the `--listInvalidSymbolLinks` argument: 

// ```
//  --listInvalidSymbolLinks  Emits a list of broken symbol [[navigation]] links after documentation generation
// ```









// ## Ignoring things


// If we don't want some class method or other entity to appear at all in TypeDoc output we use the `@hidden` tag. 

// **Important**: Put `@hidden` at the very top of the comment related to the entity you want to ignore. 

// You can ignore any entity that can be documented with its own comment, for example classes, methods, properties, etc. But you can't ignore parameters or return values because these doesn't have its own comment. 

// In the following example, the output will only contain `method2()` but not `method1()``: 


interface SomeThingsAreIgnored {
  /**
   * @hidden
   * this comment should be ignored
   * 
   */
  method1():Promise<void>;
  /**
   * this comment shouldn't be ignored
   */
  method2():string;
}

// Here you can see the output generated by TypeDoc: [interfaces/somethingsareignored](../../interfaces/somethingsareignored.html).

// The following example makes TypeDoc to ignore the whole class: 


/** @hidden */
export class ClassTotallyIgnored {
  color:string;
}

// Here you can see the output generated by TypeDoc: [classes/classtotallyignored](../../classes/classtotallyignored.html).



// ### Filter non public or non exported entities globally

// You can also configure TypeDoc tool to ignore all entities that are not public or all entities that are not exported. For that you must use the configuration options: 
// ```
//  --exclude                 Define patterns for excluded files when specifying paths.
//  --excludeExternals        Prevent externally resolved TypeScript files from being documented.
//  --excludeNotExported      Prevent symbols that are not exported from being documented.
//  --excludePrivate          Ignores private variables and methods
//  --excludeProtected
// ```
// More details [in the configuration section](#configuring-typedoc-tool)








// ## Configuring TypeDoc tool

//  * all options should be http://typedoc.org/guides/usage/











// <script src="https://cancerberosgx.github.io/raphaeljs-tutorial/generated_toc.js"></script>
// <style>
// h1, h2, h3, h4, h5, h6{
//   text-transform: none;
// }</style>
